/* This file is autogenerated, do not edit*/
#include "obs-websocket_automoc.dir/moc_WSEvents_X2RS6NZEQLVKV7.cpp"
#include "obs-websocket_automoc.dir/moc_WSRequestHandl_OBIODUEQVRGEL2.cpp"
#include "obs-websocket_automoc.dir/moc_WSServer_PVQE2JNUWSKD72.cpp"
#include "obs-websocket_automoc.dir/moc_settings-dialo_7AS5GEUKLQJRVS.cpp"
